config/routes.rb
Rails.application.routes.draw do
  root 'billboards#index'

  resources :billboards

  get 'new_billboard_song/:id', to: 'billboards#new_song', as: 'new_billboard_song'
	post 'add_billboard_song/:id/:song_id', to: 'billboards#add_song', as: 'add_billboard_song'
	delete 'remove_billboard_song/:id/:song_id', to: 'billboards#remove_song', as: 'remove_billboard_song'

  resources :artists do
    resources :songs
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
  validates_presence_of :name, :genre
end

app/models/billboard.rb
class Billboard < ApplicationRecord
  has_many :songs
  validates_presence_of :name
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist

  def info
    "#{self.title} - #{self.artist.name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  def index
    @artists = Artist.all
  end

  def show
  end

  def edit
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      redirect_to @artist
    else
      render :new
    end
  end

  def update
    if @artist.update(artist_params)
      redirect_to @artist
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy
    redirect_to
  end

  private

    def set_artist
      @artist = Artist.find(params[:id])
    end

    def artist_params
      params.require(:artist).permit(:name, :genre, :age, :avatar)
    end
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController

  before_action :set_billboard, except: [:index, :new, :create]

  def index
    @billboards = Billboard.all
  end

  def show
    @songs = @billboard.songs
  end

  def new
    @billboard = Billboard.new
  end

  def edit
  end

  def create
    @billboard = Billboard.new(billboard_params)

    if @billboard.save
      redirect_to @billboard
    else
      render :new
    end
  end

  def update
    if @billboard.update(billboard_params)
      redirect_to @billboard
    else
      render :edit
    end
  end

  def destroy
    @billboard.destroy
    redirect_to root
  end

  def new_song
    @songs = Song.all.where(billboard_id: nil)
  end

  def add_song
    @billboard.songs << Song.find(params[:song_id])
    redirect_to billboard_path(@billboard)
  end

  def remove_song
    Song.find(params[:song_id]).update(billboard_id: nil)
    redirect_to billboard_path(@billboard)
  end

  private

    def set_billboard
      @billboard = Billboard.find(params[:id])
    end

    def billboard_params
      params.require(:billboard).permit(:name)
    end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_artist
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  def index
    @songs = @artist.songs.all
  end

  def show
  end

  def edit
  end

  def new
    @song = @artist.songs.new
  end

  def create
    @song =  @artist.songs.new(song_params)

    if @song.save
      redirect_to artist_song_path(@artist, @song)
    else
      render :new
    end
  end

  def update
    if @song.update(song_params)
      redirect_to artist_song_path(@artist, @song)
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    redirect_to artist_songs_path(@artist)
  end

  private

    def set_song
      @song = @artist.songs.find(params[:id])
    end

    def set_artist
      @artist = Artist.find(params[:artist_id])
    end

    def song_params
      params.require(:song).permit(:title, :duration, :belongs_to, :belongs_to)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for(artist) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :genre %>
  <%= f.text_field :genre %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.label :avatar %>
  <%= f.text_field :avatar %>
  
  <%= f.submit %>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist<%= @artist.name %></h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Show', @artist %>
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<h1>Artists</h1>
<%= link_to 'New Artist', new_artist_path %>
<hr />

<div class="ui grid">
  <% @artists.each do |artist| %>
    <div class="sixteen wide mobile weight wide tablet four wide computer column">
      <div class="ui fluid card">
        <div class="ui medium image">
          <img src="<%= artist.avatar %>" />
        </div>
        <div class="content">
          <%=
          link_to "#{artist.name}", artist, class: "center aligned header"%>
        </div>
        <div class="center aligned extra content">
          <div class="ui two buttons">
            <div class="green button basic">
              <%= link_to "Edit", edit_artist_path(artist) %>
            </div>
            <div class="red button basic">
              <%= link_to "Remove", artist,
               method: :delete,
               data: { confirm: 'Are you sure?'}
              %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<button class="ui button">
  <%= link_to 'Back', billboards_path %>
</button>

app/views/artists/new.html.erb
<h1>Enter New Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<h1 class="ui header center aligned"><%= @artist.name %></h1>

<div class="ui container center aligned">
  <div class="ui centered card">
    <div class="ui image medium">
      <img src="<%= @artist.avatar %>">
    </div>
    <div class="content">
      <a class="header"><%= @artist.genre %></a>
      <div class="link">
        <span class="link"><%= link_to 'All Songs', artist_songs_path(@artist) %></span>
      </div>
    </div>
  </div>
</div>

<div class="ui container center aligned">
  <button class="ui button">
    <%= link_to 'Back to Artists', artists_path %>
  </button>
</div>

app/views/billboards/_form.html.erb
<%= form_for(billboard) do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.submit nil, class: 'btn' %>
<% end %>

app/views/billboards/edit.html.erb
<h1>Editing Billboard</h1>

<%= render 'form', billboard: @billboard %>

<%= link_to 'Show', @billboard %>
<%= link_to 'Back', billboards_path %>

app/views/billboards/index.html.erb
<h1 class="ui huge header center aligned">Billboards</h1>

<table class="ui celled table">
  <thead class="center aligned">
    <tr>
      <th>Billboard Title</th>
      <th>Song Count</th>
    </tr>
  </thead>
  <tbody>
    <% @billboards.each do |billboard| %>
    <tr class="center aligned">
      <td><%= link_to billboard.name, billboard_path(billboard) %></td>
      <td><%= billboard.songs.count %></td>
    </tr>
  </tbody>
  <% end %>
</table>

<div class="ui segment center aligned">
  <button class="ui button"><%= link_to 'New Billboard', new_billboard_path %></button>
  <button class="ui button"><%= link_to 'Artists', artists_path %></button>
</div>

app/views/billboards/new.html.erb
<h1>Create New Billboard</h1>

<%= render 'form', billboard: @billboard %>

<%= link_to 'Back', billboards_path %>

app/views/billboards/new_song.html.erb
<h1>Add Song to: <%= @billboard.name %></h1>

<ul>
  <% @songs.each do |song| %>
    <li>
      <%= link_to song.info, add_billboard_song_path(@billboard, song), method: :post %>
    </li>
  <% end %>
</ul>

<%= link_to 'Back', billboards_path %>

app/views/billboards/show.html.erb
<h1 class="ui huge header"><%= @billboard.name %></h1>
<hr />

<% @songs.each do |song| %>
  <h3 class="ui header"><%= song.title %></h3>
  <h4><i><%= song.artist.name %></i></h4>
  <p><%= song.duration %></p>

  <%= link_to 'View Artist', artist_path(song.artist) %>
  <br>
  <%= link_to 'View Song', artist_song_path(song.artist, song) %>
  <br>
  <%= link_to 'Remove Song', remove_billboard_song_path(@billboard, song), method: :delete %>
  <hr />
<% end %>

<%= link_to 'Add Song', new_billboard_song_path(@billboard) %>
<br>
<%= link_to 'Edit Billboard', edit_billboard_path(@billboard) %>
<br>
<%= link_to 'Back', billboards_path %>

app/views/layouts/_navbar.html.erb
<div class="ui segment center aligned">
  <button class="ui button">
    <%= link_to 'Home', billboards_path %>
  </button>
  <button class="ui button">
    <%= link_to 'Artists', artists_path %>
  </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music Billboard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container ui">
      <%= render "layouts/navbar" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_for [@artist, @song] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :duration %>
  <%= f.text_field :duration %>

  <%= f.submit %>
  <hr />
<% end %>

app/views/songs/edit.html.erb
<h1>Editing: <%= @song.title %></h1>

<%= render 'form', song: @song %>

<%= link_to 'View Song', artist_song_path(@artist, @song) %>
<%= link_to 'Back', artist_songs_path(@artist) %>

app/views/songs/index.html.erb
<h1 class="ui header center aligned">Songs</h1>

<table class="ui celled padded table">
  <thead class="center aligned">
    <tr>
      <th>Song Title</th>
      <th>Song Duration</th>
    </tr>
  </thead>
  <tbody>
    <% @songs.each do |song| %>
    <tr class="center aligned">
      <td>
        <strong><%= link_to song.title, artist_song_path(@artist, song) %></strong>
      </td>
      <td><%= song.duration %></td>
    </tr>
  </tbody>
  <% end %>
</table>

<div class="ui contianer">
  <button class="ui button">
    <%= link_to 'Back', artist_path(@artist) %>
  </button>
  <button class="ui button">
    <%= link_to 'New Song', new_artist_song_path(@artist) %>
  </button>
</div>

app/views/songs/new.html.erb
<h1>Enter New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', artist_songs_path(@artist) %>

app/views/songs/show.html.erb
<h1>Song: <%= @song.title %></h1>

<br />

<h2>Duration: <%= @song.duration %></h2>

<hr />

<%= link_to 'Edit', edit_artist_song_path(@artist, @song) %>
<%= link_to 'Back', artist_songs_path(@artist) %>